# Generated by Django 3.2.5 on 2022-06-15 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(default='', upload_to='images/article/cover/')),
                ('datetime', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('html', models.FileField(upload_to='article/')),
                ('category', models.CharField(choices=[('人物專訪', '人物專訪'), ('轉型日記', '轉型日記'), ('新知報導', '新知報導')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/article/content/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
