# Generated by Django 3.2.5 on 2022-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('cto', '人物專訪'), ('vlog', '轉型日記'), ('newinfo', '新知報導')], max_length=255),
        ),
    ]
