# Generated by Django 3.2.5 on 2022-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/cover/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.FileField(upload_to='articles/content/'),
        ),
    ]
