# Generated by Django 3.2.5 on 2022-06-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220621_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='uploads/articles/cover/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.FileField(upload_to='uploads/articles/content/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='uploads/videos/'),
        ),
    ]
