# Generated by Django 3.2.5 on 2022-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='static/articles/cover/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html',
            field=models.FileField(upload_to='static/articles/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.FileField(upload_to='static/articles/content/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='static/videos/'),
        ),
    ]
