# Generated by Django 3.2.5 on 2022-06-22 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220621_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='article',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
