# Generated by Django 3.2.5 on 2022-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220622_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(),
        ),
    ]
