# Generated by Django 3.2.5 on 2022-06-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='feature_file',
            new_name='html',
        ),
    ]
