# Generated by Django 3.2.5 on 2022-06-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_featureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_index',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
