# Generated by Django 3.2.5 on 2022-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220715_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index_image',
            field=models.ImageField(blank=True, upload_to='static/articles/cover/'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='static/articles/cover/'),
        ),
    ]
