# Generated by Django 3.2.5 on 2022-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220720_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_image',
            field=models.ImageField(upload_to='static/articles/index/'),
        ),
    ]
