# Generated by Django 3.2.5 on 2022-07-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_article_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_image',
            field=models.ImageField(blank=True, upload_to='static/articles/index/'),
        ),
    ]
