# Generated by Django 3.2.5 on 2022-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaHourlyUsageByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(db_column='TYPE_NAME')),
                ('type_level', models.TextField(db_column='TYPE_LEVEL')),
                ('date', models.DateTimeField(db_column='DATE')),
                ('weekday_name_abbreviated', models.TextField(db_column='WEEKDAY_NAME_ABBREVIATED')),
                ('hour', models.BigIntegerField(db_column='HOUR')),
                ('number_of_users', models.BigIntegerField(db_column='NUMBER_OF_USERS')),
            ],
            options={
                'db_table': 'SA_HOURLY_USAGE_BY_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaHourlyUsageOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='DATE')),
                ('weekday_name_abbreviated', models.TextField(db_column='WEEKDAY_NAME_ABBREVIATED')),
                ('hour', models.BigIntegerField(db_column='HOUR')),
                ('number_of_users', models.BigIntegerField(db_column='NUMBER_OF_USERS')),
            ],
            options={
                'db_table': 'SA_HOURLY_USAGE_OVERVIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaRegularUsersByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(db_column='WEEK_NUMBER')),
                ('type_name', models.TextField(db_column='TYPE_NAME')),
                ('type_level', models.TextField(db_column='TYPE_LEVEL')),
                ('avg_usage_over_3_days', models.BigIntegerField(db_column='AVG_USAGE_OVER_3_DAYS')),
                ('avg_usage_2_days', models.BigIntegerField(db_column='AVG_USAGE_2_DAYS')),
                ('avg_usage_1_days', models.BigIntegerField(db_column='AVG_USAGE_1_DAYS')),
                ('opened_sa_in_four_weeks', models.BigIntegerField(db_column='OPENED_SA_IN_FOUR_WEEKS')),
                ('regular_percentage', models.FloatField(db_column='REGULAR_PERCENTAGE')),
            ],
            options={
                'db_table': 'SA_REGULAR_USERS_BY_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaRegularUsersOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.BigIntegerField(db_column='WEEK_NUMBER')),
                ('avg_usage_over_3_days', models.BigIntegerField(db_column='AVG_USAGE_OVER_3_DAYS')),
                ('avg_usage_2_days', models.BigIntegerField(db_column='AVG_USAGE_2_DAYS')),
                ('avg_usage_1_days', models.BigIntegerField(db_column='AVG_USAGE_1_DAYS')),
                ('opened_sa_in_four_weeks', models.BigIntegerField(db_column='OPENED_SA_IN_FOUR_WEEKS')),
                ('regular_percentage', models.FloatField(db_column='REGULAR_PERCENTAGE')),
            ],
            options={
                'db_table': 'SA_REGULAR_USERS_OVERVIEW',
                'managed': False,
            },
        ),
    ]
